# Configuration for local hooks (e.g. installed via pipx).
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      args: [
        "--force-single-line-imports",
        "--lines-after-imports=2",
        "--project=my_package",
        "--known-local-folder=setup",
      ]
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: ["--extend-ignore=E501"]
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
